name = "vectorize-mcp-worker"
main = "src/index.ts"
compatibility_date = "2025-12-02"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "mcp-knowledge-base"

[[d1_databases]]
binding = "DB"
database_name = "mcp-knowledge-db"
database_id = "acba4671-52e3-458e-8115-d000f31c32b1"

[observability]
enabled = true

# wrangler secret put API_KEY